### ISSUE TITLE
Sketch 56.3 Not working

### ISSUE THREAD

**Issue by faridsabitov** [KikeSz/Method-Sketch-Plugin#1]
Hi KikeSz,

First of all, thank you for such an amazing plugin! I tried to use it and looks like Method is not working with Sketch higher than 56.3.

The round feature is not working and when I'm trying to open settings I see this error in DevTools.

MOJavaScriptException: Error: An Obj-C exception occurred.
[native code]
s SketchAPI.js:1:149248
settings script.js:17:1
__skpm_run script.js:280:17
__skpm_run [native code]

I hope it will not take a lot of effort to fix it!

Thank you,
Farid

**Comment by KikeSz** [comment]
It's solved!

If you make a mistake, tell me and I'll try to fix it.

**Comment by faridsabitov** [comment]
Works perfectly, thank you!
